keycloak:
  build: "."
  command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]
  volumes:
    - ./realm-config/master-realm.json:/opt/jboss/keycloak/realm-config/master-realm.json
    - ./realm-config/master-users.json:/opt/jboss/keycloak/realm-config/master-users-0.json
    - ./realm-config/realm.json:/opt/jboss/keycloak/realm-config/ACME-realm.json
    - ./realm-config/users.json:/opt/jboss/keycloak/realm-config/ACME-users-0.json
    - ./data:/opt/jboss/keycloak/standalone/data
  environment:
    - KEYCLOAK_LOGLEVEL=DEBUG
    - KEYCLOAK_THEME_STATIC_MAX_AGE=-1
    - KEYCLOAK_THEME_CACHE_THEMES=false
    - KEYCLOAK_THEME_CACHE_TEMPLATES=false
  ports:
    - 9080:8080
    - 9443:9443
    - 10990:10990
